import 'package:flutter/material.dart';

//
// const lightColorScheme = ColorScheme(
//   brightness: Brightness.light,
//   primary: Color(0xFF6750A4),
//   onPrimary: Color(0xFFFFFFFF),
//   primaryContainer: Color(0xFFE9DDFF),
//   onPrimaryContainer: Color(0xFF22005D),
//   secondary: Color(0xFF684FA4),
//   onSecondary: Color(0xFFFFFFFF),
//   secondaryContainer: Color(0xFFE9DDFF),
//   onSecondaryContainer: Color(0xFF23005C),
//   tertiary: Color(0xFF984062),
//   onTertiary: Color(0xFFFFFFFF),
//   tertiaryContainer: Color(0xFFFFD9E3),
//   onTertiaryContainer: Color(0xFF3E001E),
//   error: Color(0xFFBA1A1A),
//   errorContainer: Color(0xFFFFDAD6),
//   onError: Color(0xFFFFFFFF),
//   onErrorContainer: Color(0xFF410002),
//   background: Color(0xFFFFFBFF),
//   onBackground: Color(0xFF1C1B1E),
//   surface: Color(0xFFFFFBFF),
//   onSurface: Color(0xFF1C1B1E),
//   surfaceVariant: Color(0xFFE7E0EB),
//   onSurfaceVariant: Color(0xFF49454E),
//   outline: Color(0xFF7A757F),
//   onInverseSurface: Color(0xFFF4EFF4),
//   inverseSurface: Color(0xFF313033),
//   inversePrimary: Color(0xFFCFBCFF),
//   shadow: Color(0xFF000000),
//   surfaceTint: Color(0xFF6750A4),
//   outlineVariant: Color(0xFFCAC4CF),
//   scrim: Color(0xFF000000),
// );
//
// const darkColorScheme = ColorScheme(
//   brightness: Brightness.dark,
//   primary: Color(0xFFCFBCFF),
//   onPrimary: Color(0xFF381E72),
//   primaryContainer: Color(0xFF4F378A),
//   onPrimaryContainer: Color(0xFFE9DDFF),
//   secondary: Color(0xFFD0BCFF),
//   onSecondary: Color(0xFF381E72),
//   secondaryContainer: Color(0xFF4F378A),
//   onSecondaryContainer: Color(0xFFE9DDFF),
//   tertiary: Color(0xFFFFB0C9),
//   onTertiary: Color(0xFF5E1134),
//   tertiaryContainer: Color(0xFF7B294A),
//   onTertiaryContainer: Color(0xFFFFD9E3),
//   error: Color(0xFFFFB4AB),
//   errorContainer: Color(0xFF93000A),
//   onError: Color(0xFF690005),
//   onErrorContainer: Color(0xFFFFDAD6),
//   background: Color(0xFF1C1B1E),
//   onBackground: Color(0xFFE6E1E6),
//   surface: Color(0xFF1C1B1E),
//   onSurface: Color(0xFFE6E1E6),
//   surfaceVariant: Color(0xFF49454E),
//   onSurfaceVariant: Color(0xFFCAC4CF),
//   outline: Color(0xFF948F99),
//   onInverseSurface: Color(0xFF1C1B1E),
//   inverseSurface: Color(0xFFE6E1E6),
//   inversePrimary: Color(0xFF6750A4),
//   shadow: Color(0xFF000000),
//   surfaceTint: Color(0xFFCFBCFF),
//   outlineVariant: Color(0xFF49454E),
//   scrim: Color(0xFF000000),
//  );
ColorScheme lightColorScheme = ColorScheme.fromSeed(
    seedColor: Colors.white, brightness: Brightness.light);
// const lightColorScheme = ColorScheme(
//   brightness: Brightness.light,
//   primary: Color(0xFF363740),
//   onPrimary: Color(0xFFFFFFFF),
//   primaryContainer: Color(0xFFDDE1FF),
//   onPrimaryContainer: Color(0xFF001257),
//   secondary: Color(0xFF245FA6),
//   onSecondary: Color(0xFFFFFFFF),
//   secondaryContainer: Color(0xFFD5E3FF),
//   onSecondaryContainer: Color(0xFF001B3C),
//   tertiary: Color(0xFF76546E),
//   onTertiary: Color(0xFFFFFFFF),
//   tertiaryContainer: Color(0xFFFFD7F3),
//   onTertiaryContainer: Color(0xFF2D1228),
//   error: Color(0xFFBA1A1A),
//   errorContainer: Color(0xFFFFDAD6),
//   onError: Color(0xFFFFFFFF),
//   onErrorContainer: Color(0xFF410002),
//   background: Color(0xFFFEFBFF),
//   onBackground: Color(0xFF1B1B1F),
//   surface: Color(0xFFFEFBFF),
//   onSurface: Color(0xFF1B1B1F),
//   surfaceVariant: Color(0xFFE3E1EC),
//   onSurfaceVariant: Color(0xFF45464F),
//   outline: Color(0xFF767680),
//   onInverseSurface: Color(0xFFF3F0F4),
//   inverseSurface: Color(0xFF303034),
//   inversePrimary: Color(0xFFB9C3FF),
//   shadow: Color(0xFF000000),
//   surfaceTint: Color(0xFF4758A9),
//   outlineVariant: Color(0xFFC6C5D0),
//   scrim: Color(0xFF000000),
// );
//
// const darkColorScheme = ColorScheme(
//   brightness: Brightness.dark,
//   primary: Color(0xFF64C7CC),
//   onPrimary: Color(0xFF000000),
//   primaryContainer: Color(0xFF2A4E52),
//   onPrimaryContainer: Color(0xFFFFFFFF),
//   secondary: Color(0xFF684FA4),
//   onSecondary: Color(0xFFFFFFFF),
//   secondaryContainer: Color(0xFF23005C),
//   onSecondaryContainer: Color(0xFFFFFFFF),
//   tertiary: Color(0xFF984062),
//   onTertiary: Color(0xFFFFFFFF),
//   tertiaryContainer: Color(0xFF3E001E),
//   onTertiaryContainer: Color(0xFFFFFFFF),
//   error: Color(0xFFBA1A1A),
//   errorContainer: Color(0xFFFFDAD6),
//   onError: Color(0xFF000000),
//   onErrorContainer: Color(0xFF410002),
//   background: Color(0xFF1C1B1E),
//   onBackground: Color(0xFFFFFFFF),
//   surface: Color(0xFF1C1B1E),
//   onSurface: Color(0xFFFFFFFF),
//   surfaceVariant: Color(0xFF49454E),
//   onSurfaceVariant: Color(0xFFFFFFFF),
//   outline: Color(0xFF7A757F),
//   onInverseSurface: Color(0xFF313033),
//   inverseSurface: Color(0xFFF4EFF4),
//   inversePrimary: Color(0xFFCFBCFF),
//   shadow: Color(0xFFFFFFFF),
//   surfaceTint: Color(0xFF64C7CC),
//   outlineVariant: Color(0xFFCAC4CF),
//   scrim: Color(0xFFFFFFFF),
// );

//
ColorScheme darkColorScheme =
    ColorScheme.fromSeed(seedColor: Colors.white, brightness: Brightness.dark);
