name: in_food
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  firebase_storage: ^11.1.1
  cloud_firestore: ^4.5.2
  flutter_screenutil: ^5.7.0
  get: 4.6.5
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  flutter_keyboard_visibility: ^5.4.0
  flutter_secure_storage: ^8.0.0
  intl_phone_number_input: ^0.7.3+1
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^5.0.8
  uuid: ^3.0.7
  geocoding: ^2.1.0
  intl : ^0.18.1
  google_maps_flutter: ^2.2.8
  geolocator: ^9.0.2
  lottie: ^2.3.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/home_page_icon.png
    - assets/images/home_page_bottom.png
    - assets/images/logo.png
    - assets/images/logo_blue.png
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/apple.png
    - assets/images/infood.png
    - assets/images/login_page_bottom.png
    - assets/lottie/cooking.json
    - assets/lottie/delivering.json
    - assets/lottie/waiting.json
